name = "tobble"
description = "A simple table library for Gleam"
version = "1.0.1"
licences = ["BSD-3-Clause"]
repository = { type = "github", user = "ollien", repo = "tobble" }

[dependencies]
gleam_stdlib = ">= 0.45.0 and < 2.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"
string_width = ">= 3.3.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"
birdie = ">= 1.2.4 and < 2.0.0"
